// Code generated by internal/gen. DO NOT EDIT.

package illusion

import "github.com/mlange-42/ark/ecs"

// Query0Where iterates entities matching Filter without fetching components.
type Query0Where[Filter QueryFilter] struct {
	world   *ecs.World
	filter  *ecs.Filter0
	matcher matcher
}

// InitParam implements [Param].
func (q *Query0Where[Filter]) InitParam(w *ecs.World) {
	t := termsOf[Filter]()
	q.world = w
	q.filter = ecs.NewFilter0(w).With(t.with...).Without(t.without...).Register()
	q.matcher = newMatcher(w, t)
}

// Iter starts an Ark query. Loop with Next; call Close if you stop early.
func (q *Query0Where[Filter]) Iter(rel ...ecs.Relation) ecs.Query0 {
	return q.filter.Query(rel...)
}

// Each calls fn for every matching entity.
func (q *Query0Where[Filter]) Each(fn func(ecs.Entity)) {
	query := q.filter.Query()
	for query.Next() {
		fn(query.Entity())
	}
}

// Count returns the number of matching entities.
func (q *Query0Where[Filter]) Count() int {
	query := q.filter.Query()
	n := query.Count()
	query.Close()
	return n
}

// Contains reports whether entity is alive and matches the query.
func (q *Query0Where[Filter]) Contains(entity ecs.Entity) bool {
	return q.world.Alive(entity) && q.matcher.matches(q.world, entity)
}

// Single returns the only matching entity. ok is false if there are zero or several.
func (q *Query0Where[Filter]) Single() (entity ecs.Entity, ok bool) {
	query := q.filter.Query()
	if !query.Next() {
		return entity, false
	}
	entity = query.Entity()
	if query.Next() {
		query.Close()
		return ecs.Entity{}, false
	}
	return entity, true
}

// Filter returns the underlying Ark filter.
func (q *Query0Where[Filter]) Filter() *ecs.Filter0 { return q.filter }

// Query1 fetches components A from every entity that has them.
type Query1[A any] = Query1Where[A, NoFilter]

// Query1Where fetches components A from entities that also match Filter.
type Query1Where[A any, Filter QueryFilter] struct {
	world   *ecs.World
	filter  *ecs.Filter1[A]
	mapper  *ecs.Map1[A]
	matcher matcher
}

// InitParam implements [Param].
func (q *Query1Where[A, Filter]) InitParam(w *ecs.World) {
	t := termsOf[Filter]()
	q.world = w
	q.filter = ecs.NewFilter1[A](w).With(t.with...).Without(t.without...).Register()
	q.mapper = ecs.NewMap1[A](w)
	q.matcher = newMatcher(w, t)
}

// Iter starts an Ark query. Loop with Next; call Close if you stop early.
func (q *Query1Where[A, Filter]) Iter(rel ...ecs.Relation) ecs.Query1[A] {
	return q.filter.Query(rel...)
}

// Each calls fn for every matching entity.
func (q *Query1Where[A, Filter]) Each(fn func(ecs.Entity, *A)) {
	query := q.filter.Query()
	for query.Next() {
		a := query.Get()
		fn(query.Entity(), a)
	}
}

// Count returns the number of matching entities.
func (q *Query1Where[A, Filter]) Count() int {
	query := q.filter.Query()
	n := query.Count()
	query.Close()
	return n
}

// Contains reports whether entity is alive and matches the query.
func (q *Query1Where[A, Filter]) Contains(entity ecs.Entity) bool {
	return q.world.Alive(entity) && q.mapper.HasAll(entity) && q.matcher.matches(q.world, entity)
}

// Get returns entity's components. ok is false if entity doesn't match the query.
func (q *Query1Where[A, Filter]) Get(entity ecs.Entity) (a *A, ok bool) {
	if !q.Contains(entity) {
		return nil, false
	}
	a = q.mapper.Get(entity)
	return a, true
}

// Single returns the only matching entity. ok is false if there are zero or several.
func (q *Query1Where[A, Filter]) Single() (entity ecs.Entity, a *A, ok bool) {
	query := q.filter.Query()
	if !query.Next() {
		return entity, nil, false
	}
	entity = query.Entity()
	a = query.Get()
	if query.Next() {
		query.Close()
		return ecs.Entity{}, nil, false
	}
	return entity, a, true
}

// Filter returns the underlying Ark filter.
func (q *Query1Where[A, Filter]) Filter() *ecs.Filter1[A] { return q.filter }

// Query2 fetches components A, B from every entity that has them.
type Query2[A, B any] = Query2Where[A, B, NoFilter]

// Query2Where fetches components A, B from entities that also match Filter.
type Query2Where[A, B any, Filter QueryFilter] struct {
	world   *ecs.World
	filter  *ecs.Filter2[A, B]
	mapper  *ecs.Map2[A, B]
	matcher matcher
}

// InitParam implements [Param].
func (q *Query2Where[A, B, Filter]) InitParam(w *ecs.World) {
	t := termsOf[Filter]()
	q.world = w
	q.filter = ecs.NewFilter2[A, B](w).With(t.with...).Without(t.without...).Register()
	q.mapper = ecs.NewMap2[A, B](w)
	q.matcher = newMatcher(w, t)
}

// Iter starts an Ark query. Loop with Next; call Close if you stop early.
func (q *Query2Where[A, B, Filter]) Iter(rel ...ecs.Relation) ecs.Query2[A, B] {
	return q.filter.Query(rel...)
}

// Each calls fn for every matching entity.
func (q *Query2Where[A, B, Filter]) Each(fn func(ecs.Entity, *A, *B)) {
	query := q.filter.Query()
	for query.Next() {
		a, b := query.Get()
		fn(query.Entity(), a, b)
	}
}

// Count returns the number of matching entities.
func (q *Query2Where[A, B, Filter]) Count() int {
	query := q.filter.Query()
	n := query.Count()
	query.Close()
	return n
}

// Contains reports whether entity is alive and matches the query.
func (q *Query2Where[A, B, Filter]) Contains(entity ecs.Entity) bool {
	return q.world.Alive(entity) && q.mapper.HasAll(entity) && q.matcher.matches(q.world, entity)
}

// Get returns entity's components. ok is false if entity doesn't match the query.
func (q *Query2Where[A, B, Filter]) Get(entity ecs.Entity) (a *A, b *B, ok bool) {
	if !q.Contains(entity) {
		return nil, nil, false
	}
	a, b = q.mapper.Get(entity)
	return a, b, true
}

// Single returns the only matching entity. ok is false if there are zero or several.
func (q *Query2Where[A, B, Filter]) Single() (entity ecs.Entity, a *A, b *B, ok bool) {
	query := q.filter.Query()
	if !query.Next() {
		return entity, nil, nil, false
	}
	entity = query.Entity()
	a, b = query.Get()
	if query.Next() {
		query.Close()
		return ecs.Entity{}, nil, nil, false
	}
	return entity, a, b, true
}

// Filter returns the underlying Ark filter.
func (q *Query2Where[A, B, Filter]) Filter() *ecs.Filter2[A, B] { return q.filter }

// Query3 fetches components A, B, C from every entity that has them.
type Query3[A, B, C any] = Query3Where[A, B, C, NoFilter]

// Query3Where fetches components A, B, C from entities that also match Filter.
type Query3Where[A, B, C any, Filter QueryFilter] struct {
	world   *ecs.World
	filter  *ecs.Filter3[A, B, C]
	mapper  *ecs.Map3[A, B, C]
	matcher matcher
}

// InitParam implements [Param].
func (q *Query3Where[A, B, C, Filter]) InitParam(w *ecs.World) {
	t := termsOf[Filter]()
	q.world = w
	q.filter = ecs.NewFilter3[A, B, C](w).With(t.with...).Without(t.without...).Register()
	q.mapper = ecs.NewMap3[A, B, C](w)
	q.matcher = newMatcher(w, t)
}

// Iter starts an Ark query. Loop with Next; call Close if you stop early.
func (q *Query3Where[A, B, C, Filter]) Iter(rel ...ecs.Relation) ecs.Query3[A, B, C] {
	return q.filter.Query(rel...)
}

// Each calls fn for every matching entity.
func (q *Query3Where[A, B, C, Filter]) Each(fn func(ecs.Entity, *A, *B, *C)) {
	query := q.filter.Query()
	for query.Next() {
		a, b, c := query.Get()
		fn(query.Entity(), a, b, c)
	}
}

// Count returns the number of matching entities.
func (q *Query3Where[A, B, C, Filter]) Count() int {
	query := q.filter.Query()
	n := query.Count()
	query.Close()
	return n
}

// Contains reports whether entity is alive and matches the query.
func (q *Query3Where[A, B, C, Filter]) Contains(entity ecs.Entity) bool {
	return q.world.Alive(entity) && q.mapper.HasAll(entity) && q.matcher.matches(q.world, entity)
}

// Get returns entity's components. ok is false if entity doesn't match the query.
func (q *Query3Where[A, B, C, Filter]) Get(entity ecs.Entity) (a *A, b *B, c *C, ok bool) {
	if !q.Contains(entity) {
		return nil, nil, nil, false
	}
	a, b, c = q.mapper.Get(entity)
	return a, b, c, true
}

// Single returns the only matching entity. ok is false if there are zero or several.
func (q *Query3Where[A, B, C, Filter]) Single() (entity ecs.Entity, a *A, b *B, c *C, ok bool) {
	query := q.filter.Query()
	if !query.Next() {
		return entity, nil, nil, nil, false
	}
	entity = query.Entity()
	a, b, c = query.Get()
	if query.Next() {
		query.Close()
		return ecs.Entity{}, nil, nil, nil, false
	}
	return entity, a, b, c, true
}

// Filter returns the underlying Ark filter.
func (q *Query3Where[A, B, C, Filter]) Filter() *ecs.Filter3[A, B, C] { return q.filter }

// Query4 fetches components A, B, C, D from every entity that has them.
type Query4[A, B, C, D any] = Query4Where[A, B, C, D, NoFilter]

// Query4Where fetches components A, B, C, D from entities that also match Filter.
type Query4Where[A, B, C, D any, Filter QueryFilter] struct {
	world   *ecs.World
	filter  *ecs.Filter4[A, B, C, D]
	mapper  *ecs.Map4[A, B, C, D]
	matcher matcher
}

// InitParam implements [Param].
func (q *Query4Where[A, B, C, D, Filter]) InitParam(w *ecs.World) {
	t := termsOf[Filter]()
	q.world = w
	q.filter = ecs.NewFilter4[A, B, C, D](w).With(t.with...).Without(t.without...).Register()
	q.mapper = ecs.NewMap4[A, B, C, D](w)
	q.matcher = newMatcher(w, t)
}

// Iter starts an Ark query. Loop with Next; call Close if you stop early.
func (q *Query4Where[A, B, C, D, Filter]) Iter(rel ...ecs.Relation) ecs.Query4[A, B, C, D] {
	return q.filter.Query(rel...)
}

// Each calls fn for every matching entity.
func (q *Query4Where[A, B, C, D, Filter]) Each(fn func(ecs.Entity, *A, *B, *C, *D)) {
	query := q.filter.Query()
	for query.Next() {
		a, b, c, d := query.Get()
		fn(query.Entity(), a, b, c, d)
	}
}

// Count returns the number of matching entities.
func (q *Query4Where[A, B, C, D, Filter]) Count() int {
	query := q.filter.Query()
	n := query.Count()
	query.Close()
	return n
}

// Contains reports whether entity is alive and matches the query.
func (q *Query4Where[A, B, C, D, Filter]) Contains(entity ecs.Entity) bool {
	return q.world.Alive(entity) && q.mapper.HasAll(entity) && q.matcher.matches(q.world, entity)
}

// Get returns entity's components. ok is false if entity doesn't match the query.
func (q *Query4Where[A, B, C, D, Filter]) Get(entity ecs.Entity) (a *A, b *B, c *C, d *D, ok bool) {
	if !q.Contains(entity) {
		return nil, nil, nil, nil, false
	}
	a, b, c, d = q.mapper.Get(entity)
	return a, b, c, d, true
}

// Single returns the only matching entity. ok is false if there are zero or several.
func (q *Query4Where[A, B, C, D, Filter]) Single() (entity ecs.Entity, a *A, b *B, c *C, d *D, ok bool) {
	query := q.filter.Query()
	if !query.Next() {
		return entity, nil, nil, nil, nil, false
	}
	entity = query.Entity()
	a, b, c, d = query.Get()
	if query.Next() {
		query.Close()
		return ecs.Entity{}, nil, nil, nil, nil, false
	}
	return entity, a, b, c, d, true
}

// Filter returns the underlying Ark filter.
func (q *Query4Where[A, B, C, D, Filter]) Filter() *ecs.Filter4[A, B, C, D] { return q.filter }

// Query5 fetches components A, B, C, D, E from every entity that has them.
type Query5[A, B, C, D, E any] = Query5Where[A, B, C, D, E, NoFilter]

// Query5Where fetches components A, B, C, D, E from entities that also match Filter.
type Query5Where[A, B, C, D, E any, Filter QueryFilter] struct {
	world   *ecs.World
	filter  *ecs.Filter5[A, B, C, D, E]
	mapper  *ecs.Map5[A, B, C, D, E]
	matcher matcher
}

// InitParam implements [Param].
func (q *Query5Where[A, B, C, D, E, Filter]) InitParam(w *ecs.World) {
	t := termsOf[Filter]()
	q.world = w
	q.filter = ecs.NewFilter5[A, B, C, D, E](w).With(t.with...).Without(t.without...).Register()
	q.mapper = ecs.NewMap5[A, B, C, D, E](w)
	q.matcher = newMatcher(w, t)
}

// Iter starts an Ark query. Loop with Next; call Close if you stop early.
func (q *Query5Where[A, B, C, D, E, Filter]) Iter(rel ...ecs.Relation) ecs.Query5[A, B, C, D, E] {
	return q.filter.Query(rel...)
}

// Each calls fn for every matching entity.
func (q *Query5Where[A, B, C, D, E, Filter]) Each(fn func(ecs.Entity, *A, *B, *C, *D, *E)) {
	query := q.filter.Query()
	for query.Next() {
		a, b, c, d, e := query.Get()
		fn(query.Entity(), a, b, c, d, e)
	}
}

// Count returns the number of matching entities.
func (q *Query5Where[A, B, C, D, E, Filter]) Count() int {
	query := q.filter.Query()
	n := query.Count()
	query.Close()
	return n
}

// Contains reports whether entity is alive and matches the query.
func (q *Query5Where[A, B, C, D, E, Filter]) Contains(entity ecs.Entity) bool {
	return q.world.Alive(entity) && q.mapper.HasAll(entity) && q.matcher.matches(q.world, entity)
}

// Get returns entity's components. ok is false if entity doesn't match the query.
func (q *Query5Where[A, B, C, D, E, Filter]) Get(entity ecs.Entity) (a *A, b *B, c *C, d *D, e *E, ok bool) {
	if !q.Contains(entity) {
		return nil, nil, nil, nil, nil, false
	}
	a, b, c, d, e = q.mapper.Get(entity)
	return a, b, c, d, e, true
}

// Single returns the only matching entity. ok is false if there are zero or several.
func (q *Query5Where[A, B, C, D, E, Filter]) Single() (entity ecs.Entity, a *A, b *B, c *C, d *D, e *E, ok bool) {
	query := q.filter.Query()
	if !query.Next() {
		return entity, nil, nil, nil, nil, nil, false
	}
	entity = query.Entity()
	a, b, c, d, e = query.Get()
	if query.Next() {
		query.Close()
		return ecs.Entity{}, nil, nil, nil, nil, nil, false
	}
	return entity, a, b, c, d, e, true
}

// Filter returns the underlying Ark filter.
func (q *Query5Where[A, B, C, D, E, Filter]) Filter() *ecs.Filter5[A, B, C, D, E] { return q.filter }

// Query6 fetches components A, B, C, D, E, F from every entity that has them.
type Query6[A, B, C, D, E, F any] = Query6Where[A, B, C, D, E, F, NoFilter]

// Query6Where fetches components A, B, C, D, E, F from entities that also match Filter.
type Query6Where[A, B, C, D, E, F any, Filter QueryFilter] struct {
	world   *ecs.World
	filter  *ecs.Filter6[A, B, C, D, E, F]
	mapper  *ecs.Map6[A, B, C, D, E, F]
	matcher matcher
}

// InitParam implements [Param].
func (q *Query6Where[A, B, C, D, E, F, Filter]) InitParam(w *ecs.World) {
	t := termsOf[Filter]()
	q.world = w
	q.filter = ecs.NewFilter6[A, B, C, D, E, F](w).With(t.with...).Without(t.without...).Register()
	q.mapper = ecs.NewMap6[A, B, C, D, E, F](w)
	q.matcher = newMatcher(w, t)
}

// Iter starts an Ark query. Loop with Next; call Close if you stop early.
func (q *Query6Where[A, B, C, D, E, F, Filter]) Iter(rel ...ecs.Relation) ecs.Query6[A, B, C, D, E, F] {
	return q.filter.Query(rel...)
}

// Each calls fn for every matching entity.
func (q *Query6Where[A, B, C, D, E, F, Filter]) Each(fn func(ecs.Entity, *A, *B, *C, *D, *E, *F)) {
	query := q.filter.Query()
	for query.Next() {
		a, b, c, d, e, f := query.Get()
		fn(query.Entity(), a, b, c, d, e, f)
	}
}

// Count returns the number of matching entities.
func (q *Query6Where[A, B, C, D, E, F, Filter]) Count() int {
	query := q.filter.Query()
	n := query.Count()
	query.Close()
	return n
}

// Contains reports whether entity is alive and matches the query.
func (q *Query6Where[A, B, C, D, E, F, Filter]) Contains(entity ecs.Entity) bool {
	return q.world.Alive(entity) && q.mapper.HasAll(entity) && q.matcher.matches(q.world, entity)
}

// Get returns entity's components. ok is false if entity doesn't match the query.
func (q *Query6Where[A, B, C, D, E, F, Filter]) Get(entity ecs.Entity) (a *A, b *B, c *C, d *D, e *E, f *F, ok bool) {
	if !q.Contains(entity) {
		return nil, nil, nil, nil, nil, nil, false
	}
	a, b, c, d, e, f = q.mapper.Get(entity)
	return a, b, c, d, e, f, true
}

// Single returns the only matching entity. ok is false if there are zero or several.
func (q *Query6Where[A, B, C, D, E, F, Filter]) Single() (entity ecs.Entity, a *A, b *B, c *C, d *D, e *E, f *F, ok bool) {
	query := q.filter.Query()
	if !query.Next() {
		return entity, nil, nil, nil, nil, nil, nil, false
	}
	entity = query.Entity()
	a, b, c, d, e, f = query.Get()
	if query.Next() {
		query.Close()
		return ecs.Entity{}, nil, nil, nil, nil, nil, nil, false
	}
	return entity, a, b, c, d, e, f, true
}

// Filter returns the underlying Ark filter.
func (q *Query6Where[A, B, C, D, E, F, Filter]) Filter() *ecs.Filter6[A, B, C, D, E, F] {
	return q.filter
}

// Query7 fetches components A, B, C, D, E, F, G from every entity that has them.
type Query7[A, B, C, D, E, F, G any] = Query7Where[A, B, C, D, E, F, G, NoFilter]

// Query7Where fetches components A, B, C, D, E, F, G from entities that also match Filter.
type Query7Where[A, B, C, D, E, F, G any, Filter QueryFilter] struct {
	world   *ecs.World
	filter  *ecs.Filter7[A, B, C, D, E, F, G]
	mapper  *ecs.Map7[A, B, C, D, E, F, G]
	matcher matcher
}

// InitParam implements [Param].
func (q *Query7Where[A, B, C, D, E, F, G, Filter]) InitParam(w *ecs.World) {
	t := termsOf[Filter]()
	q.world = w
	q.filter = ecs.NewFilter7[A, B, C, D, E, F, G](w).With(t.with...).Without(t.without...).Register()
	q.mapper = ecs.NewMap7[A, B, C, D, E, F, G](w)
	q.matcher = newMatcher(w, t)
}

// Iter starts an Ark query. Loop with Next; call Close if you stop early.
func (q *Query7Where[A, B, C, D, E, F, G, Filter]) Iter(rel ...ecs.Relation) ecs.Query7[A, B, C, D, E, F, G] {
	return q.filter.Query(rel...)
}

// Each calls fn for every matching entity.
func (q *Query7Where[A, B, C, D, E, F, G, Filter]) Each(fn func(ecs.Entity, *A, *B, *C, *D, *E, *F, *G)) {
	query := q.filter.Query()
	for query.Next() {
		a, b, c, d, e, f, g := query.Get()
		fn(query.Entity(), a, b, c, d, e, f, g)
	}
}

// Count returns the number of matching entities.
func (q *Query7Where[A, B, C, D, E, F, G, Filter]) Count() int {
	query := q.filter.Query()
	n := query.Count()
	query.Close()
	return n
}

// Contains reports whether entity is alive and matches the query.
func (q *Query7Where[A, B, C, D, E, F, G, Filter]) Contains(entity ecs.Entity) bool {
	return q.world.Alive(entity) && q.mapper.HasAll(entity) && q.matcher.matches(q.world, entity)
}

// Get returns entity's components. ok is false if entity doesn't match the query.
func (q *Query7Where[A, B, C, D, E, F, G, Filter]) Get(entity ecs.Entity) (a *A, b *B, c *C, d *D, e *E, f *F, g *G, ok bool) {
	if !q.Contains(entity) {
		return nil, nil, nil, nil, nil, nil, nil, false
	}
	a, b, c, d, e, f, g = q.mapper.Get(entity)
	return a, b, c, d, e, f, g, true
}

// Single returns the only matching entity. ok is false if there are zero or several.
func (q *Query7Where[A, B, C, D, E, F, G, Filter]) Single() (entity ecs.Entity, a *A, b *B, c *C, d *D, e *E, f *F, g *G, ok bool) {
	query := q.filter.Query()
	if !query.Next() {
		return entity, nil, nil, nil, nil, nil, nil, nil, false
	}
	entity = query.Entity()
	a, b, c, d, e, f, g = query.Get()
	if query.Next() {
		query.Close()
		return ecs.Entity{}, nil, nil, nil, nil, nil, nil, nil, false
	}
	return entity, a, b, c, d, e, f, g, true
}

// Filter returns the underlying Ark filter.
func (q *Query7Where[A, B, C, D, E, F, G, Filter]) Filter() *ecs.Filter7[A, B, C, D, E, F, G] {
	return q.filter
}

// Query8 fetches components A, B, C, D, E, F, G, H from every entity that has them.
type Query8[A, B, C, D, E, F, G, H any] = Query8Where[A, B, C, D, E, F, G, H, NoFilter]

// Query8Where fetches components A, B, C, D, E, F, G, H from entities that also match Filter.
type Query8Where[A, B, C, D, E, F, G, H any, Filter QueryFilter] struct {
	world   *ecs.World
	filter  *ecs.Filter8[A, B, C, D, E, F, G, H]
	mapper  *ecs.Map8[A, B, C, D, E, F, G, H]
	matcher matcher
}

// InitParam implements [Param].
func (q *Query8Where[A, B, C, D, E, F, G, H, Filter]) InitParam(w *ecs.World) {
	t := termsOf[Filter]()
	q.world = w
	q.filter = ecs.NewFilter8[A, B, C, D, E, F, G, H](w).With(t.with...).Without(t.without...).Register()
	q.mapper = ecs.NewMap8[A, B, C, D, E, F, G, H](w)
	q.matcher = newMatcher(w, t)
}

// Iter starts an Ark query. Loop with Next; call Close if you stop early.
func (q *Query8Where[A, B, C, D, E, F, G, H, Filter]) Iter(rel ...ecs.Relation) ecs.Query8[A, B, C, D, E, F, G, H] {
	return q.filter.Query(rel...)
}

// Each calls fn for every matching entity.
func (q *Query8Where[A, B, C, D, E, F, G, H, Filter]) Each(fn func(ecs.Entity, *A, *B, *C, *D, *E, *F, *G, *H)) {
	query := q.filter.Query()
	for query.Next() {
		a, b, c, d, e, f, g, h := query.Get()
		fn(query.Entity(), a, b, c, d, e, f, g, h)
	}
}

// Count returns the number of matching entities.
func (q *Query8Where[A, B, C, D, E, F, G, H, Filter]) Count() int {
	query := q.filter.Query()
	n := query.Count()
	query.Close()
	return n
}

// Contains reports whether entity is alive and matches the query.
func (q *Query8Where[A, B, C, D, E, F, G, H, Filter]) Contains(entity ecs.Entity) bool {
	return q.world.Alive(entity) && q.mapper.HasAll(entity) && q.matcher.matches(q.world, entity)
}

// Get returns entity's components. ok is false if entity doesn't match the query.
func (q *Query8Where[A, B, C, D, E, F, G, H, Filter]) Get(entity ecs.Entity) (a *A, b *B, c *C, d *D, e *E, f *F, g *G, h *H, ok bool) {
	if !q.Contains(entity) {
		return nil, nil, nil, nil, nil, nil, nil, nil, false
	}
	a, b, c, d, e, f, g, h = q.mapper.Get(entity)
	return a, b, c, d, e, f, g, h, true
}

// Single returns the only matching entity. ok is false if there are zero or several.
func (q *Query8Where[A, B, C, D, E, F, G, H, Filter]) Single() (entity ecs.Entity, a *A, b *B, c *C, d *D, e *E, f *F, g *G, h *H, ok bool) {
	query := q.filter.Query()
	if !query.Next() {
		return entity, nil, nil, nil, nil, nil, nil, nil, nil, false
	}
	entity = query.Entity()
	a, b, c, d, e, f, g, h = query.Get()
	if query.Next() {
		query.Close()
		return ecs.Entity{}, nil, nil, nil, nil, nil, nil, nil, nil, false
	}
	return entity, a, b, c, d, e, f, g, h, true
}

// Filter returns the underlying Ark filter.
func (q *Query8Where[A, B, C, D, E, F, G, H, Filter]) Filter() *ecs.Filter8[A, B, C, D, E, F, G, H] {
	return q.filter
}
