// Code generated by internal/gen. DO NOT EDIT.

package illusion

import "github.com/mlange-42/ark/ecs"

// Fn0 turns a function with no parameters into a system.
func Fn0(f func()) *SystemConfig {
	return newSystemConfig(funcName(f), &fn0{f: f})
}

type fn0 struct {
	f func()
}

func (s *fn0) Init(*ecs.World) {}

func (s *fn0) Run(*ecs.World) { s.f() }

// Cond0 turns a function with no parameters that returns bool into a run condition.
func Cond0(f func() bool) Condition {
	return &cond0{f: f}
}

type cond0 struct {
	f func() bool
}

func (s *cond0) Init(*ecs.World) {}

func (s *cond0) Check(*ecs.World) bool { return s.f() }

// Fn1 turns a function with 1 parameter into a system.
func Fn1[A any, PA paramPtr[A]](f func(PA)) *SystemConfig {
	return newSystemConfig(funcName(f), &fn1[A, PA]{f: f})
}

type fn1[A any, PA paramPtr[A]] struct {
	f  func(PA)
	pa A
}

func (s *fn1[A, PA]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
}

func (s *fn1[A, PA]) Run(*ecs.World) { s.f(&s.pa) }

// Cond1 turns a function with 1 parameter that returns bool into a run condition.
func Cond1[A any, PA paramPtr[A]](f func(PA) bool) Condition {
	return &cond1[A, PA]{f: f}
}

type cond1[A any, PA paramPtr[A]] struct {
	f  func(PA) bool
	pa A
}

func (s *cond1[A, PA]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
}

func (s *cond1[A, PA]) Check(*ecs.World) bool { return s.f(&s.pa) }

// Fn2 turns a function with 2 parameters into a system.
func Fn2[A, B any, PA paramPtr[A], PB paramPtr[B]](f func(PA, PB)) *SystemConfig {
	return newSystemConfig(funcName(f), &fn2[A, B, PA, PB]{f: f})
}

type fn2[A, B any, PA paramPtr[A], PB paramPtr[B]] struct {
	f  func(PA, PB)
	pa A
	pb B
}

func (s *fn2[A, B, PA, PB]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
}

func (s *fn2[A, B, PA, PB]) Run(*ecs.World) { s.f(&s.pa, &s.pb) }

// Cond2 turns a function with 2 parameters that returns bool into a run condition.
func Cond2[A, B any, PA paramPtr[A], PB paramPtr[B]](f func(PA, PB) bool) Condition {
	return &cond2[A, B, PA, PB]{f: f}
}

type cond2[A, B any, PA paramPtr[A], PB paramPtr[B]] struct {
	f  func(PA, PB) bool
	pa A
	pb B
}

func (s *cond2[A, B, PA, PB]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
}

func (s *cond2[A, B, PA, PB]) Check(*ecs.World) bool { return s.f(&s.pa, &s.pb) }

// Fn3 turns a function with 3 parameters into a system.
func Fn3[A, B, C any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C]](f func(PA, PB, PC)) *SystemConfig {
	return newSystemConfig(funcName(f), &fn3[A, B, C, PA, PB, PC]{f: f})
}

type fn3[A, B, C any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C]] struct {
	f  func(PA, PB, PC)
	pa A
	pb B
	pc C
}

func (s *fn3[A, B, C, PA, PB, PC]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
	PC(&s.pc).InitParam(w)
}

func (s *fn3[A, B, C, PA, PB, PC]) Run(*ecs.World) { s.f(&s.pa, &s.pb, &s.pc) }

// Cond3 turns a function with 3 parameters that returns bool into a run condition.
func Cond3[A, B, C any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C]](f func(PA, PB, PC) bool) Condition {
	return &cond3[A, B, C, PA, PB, PC]{f: f}
}

type cond3[A, B, C any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C]] struct {
	f  func(PA, PB, PC) bool
	pa A
	pb B
	pc C
}

func (s *cond3[A, B, C, PA, PB, PC]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
	PC(&s.pc).InitParam(w)
}

func (s *cond3[A, B, C, PA, PB, PC]) Check(*ecs.World) bool { return s.f(&s.pa, &s.pb, &s.pc) }

// Fn4 turns a function with 4 parameters into a system.
func Fn4[A, B, C, D any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D]](f func(PA, PB, PC, PD)) *SystemConfig {
	return newSystemConfig(funcName(f), &fn4[A, B, C, D, PA, PB, PC, PD]{f: f})
}

type fn4[A, B, C, D any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D]] struct {
	f  func(PA, PB, PC, PD)
	pa A
	pb B
	pc C
	pd D
}

func (s *fn4[A, B, C, D, PA, PB, PC, PD]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
	PC(&s.pc).InitParam(w)
	PD(&s.pd).InitParam(w)
}

func (s *fn4[A, B, C, D, PA, PB, PC, PD]) Run(*ecs.World) { s.f(&s.pa, &s.pb, &s.pc, &s.pd) }

// Cond4 turns a function with 4 parameters that returns bool into a run condition.
func Cond4[A, B, C, D any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D]](f func(PA, PB, PC, PD) bool) Condition {
	return &cond4[A, B, C, D, PA, PB, PC, PD]{f: f}
}

type cond4[A, B, C, D any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D]] struct {
	f  func(PA, PB, PC, PD) bool
	pa A
	pb B
	pc C
	pd D
}

func (s *cond4[A, B, C, D, PA, PB, PC, PD]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
	PC(&s.pc).InitParam(w)
	PD(&s.pd).InitParam(w)
}

func (s *cond4[A, B, C, D, PA, PB, PC, PD]) Check(*ecs.World) bool {
	return s.f(&s.pa, &s.pb, &s.pc, &s.pd)
}

// Fn5 turns a function with 5 parameters into a system.
func Fn5[A, B, C, D, E any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E]](f func(PA, PB, PC, PD, PE)) *SystemConfig {
	return newSystemConfig(funcName(f), &fn5[A, B, C, D, E, PA, PB, PC, PD, PE]{f: f})
}

type fn5[A, B, C, D, E any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E]] struct {
	f  func(PA, PB, PC, PD, PE)
	pa A
	pb B
	pc C
	pd D
	pe E
}

func (s *fn5[A, B, C, D, E, PA, PB, PC, PD, PE]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
	PC(&s.pc).InitParam(w)
	PD(&s.pd).InitParam(w)
	PE(&s.pe).InitParam(w)
}

func (s *fn5[A, B, C, D, E, PA, PB, PC, PD, PE]) Run(*ecs.World) {
	s.f(&s.pa, &s.pb, &s.pc, &s.pd, &s.pe)
}

// Cond5 turns a function with 5 parameters that returns bool into a run condition.
func Cond5[A, B, C, D, E any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E]](f func(PA, PB, PC, PD, PE) bool) Condition {
	return &cond5[A, B, C, D, E, PA, PB, PC, PD, PE]{f: f}
}

type cond5[A, B, C, D, E any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E]] struct {
	f  func(PA, PB, PC, PD, PE) bool
	pa A
	pb B
	pc C
	pd D
	pe E
}

func (s *cond5[A, B, C, D, E, PA, PB, PC, PD, PE]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
	PC(&s.pc).InitParam(w)
	PD(&s.pd).InitParam(w)
	PE(&s.pe).InitParam(w)
}

func (s *cond5[A, B, C, D, E, PA, PB, PC, PD, PE]) Check(*ecs.World) bool {
	return s.f(&s.pa, &s.pb, &s.pc, &s.pd, &s.pe)
}

// Fn6 turns a function with 6 parameters into a system.
func Fn6[A, B, C, D, E, F any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E], PF paramPtr[F]](f func(PA, PB, PC, PD, PE, PF)) *SystemConfig {
	return newSystemConfig(funcName(f), &fn6[A, B, C, D, E, F, PA, PB, PC, PD, PE, PF]{f: f})
}

type fn6[A, B, C, D, E, F any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E], PF paramPtr[F]] struct {
	f  func(PA, PB, PC, PD, PE, PF)
	pa A
	pb B
	pc C
	pd D
	pe E
	pf F
}

func (s *fn6[A, B, C, D, E, F, PA, PB, PC, PD, PE, PF]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
	PC(&s.pc).InitParam(w)
	PD(&s.pd).InitParam(w)
	PE(&s.pe).InitParam(w)
	PF(&s.pf).InitParam(w)
}

func (s *fn6[A, B, C, D, E, F, PA, PB, PC, PD, PE, PF]) Run(*ecs.World) {
	s.f(&s.pa, &s.pb, &s.pc, &s.pd, &s.pe, &s.pf)
}

// Cond6 turns a function with 6 parameters that returns bool into a run condition.
func Cond6[A, B, C, D, E, F any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E], PF paramPtr[F]](f func(PA, PB, PC, PD, PE, PF) bool) Condition {
	return &cond6[A, B, C, D, E, F, PA, PB, PC, PD, PE, PF]{f: f}
}

type cond6[A, B, C, D, E, F any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E], PF paramPtr[F]] struct {
	f  func(PA, PB, PC, PD, PE, PF) bool
	pa A
	pb B
	pc C
	pd D
	pe E
	pf F
}

func (s *cond6[A, B, C, D, E, F, PA, PB, PC, PD, PE, PF]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
	PC(&s.pc).InitParam(w)
	PD(&s.pd).InitParam(w)
	PE(&s.pe).InitParam(w)
	PF(&s.pf).InitParam(w)
}

func (s *cond6[A, B, C, D, E, F, PA, PB, PC, PD, PE, PF]) Check(*ecs.World) bool {
	return s.f(&s.pa, &s.pb, &s.pc, &s.pd, &s.pe, &s.pf)
}

// Fn7 turns a function with 7 parameters into a system.
func Fn7[A, B, C, D, E, F, G any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E], PF paramPtr[F], PG paramPtr[G]](f func(PA, PB, PC, PD, PE, PF, PG)) *SystemConfig {
	return newSystemConfig(funcName(f), &fn7[A, B, C, D, E, F, G, PA, PB, PC, PD, PE, PF, PG]{f: f})
}

type fn7[A, B, C, D, E, F, G any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E], PF paramPtr[F], PG paramPtr[G]] struct {
	f  func(PA, PB, PC, PD, PE, PF, PG)
	pa A
	pb B
	pc C
	pd D
	pe E
	pf F
	pg G
}

func (s *fn7[A, B, C, D, E, F, G, PA, PB, PC, PD, PE, PF, PG]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
	PC(&s.pc).InitParam(w)
	PD(&s.pd).InitParam(w)
	PE(&s.pe).InitParam(w)
	PF(&s.pf).InitParam(w)
	PG(&s.pg).InitParam(w)
}

func (s *fn7[A, B, C, D, E, F, G, PA, PB, PC, PD, PE, PF, PG]) Run(*ecs.World) {
	s.f(&s.pa, &s.pb, &s.pc, &s.pd, &s.pe, &s.pf, &s.pg)
}

// Cond7 turns a function with 7 parameters that returns bool into a run condition.
func Cond7[A, B, C, D, E, F, G any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E], PF paramPtr[F], PG paramPtr[G]](f func(PA, PB, PC, PD, PE, PF, PG) bool) Condition {
	return &cond7[A, B, C, D, E, F, G, PA, PB, PC, PD, PE, PF, PG]{f: f}
}

type cond7[A, B, C, D, E, F, G any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E], PF paramPtr[F], PG paramPtr[G]] struct {
	f  func(PA, PB, PC, PD, PE, PF, PG) bool
	pa A
	pb B
	pc C
	pd D
	pe E
	pf F
	pg G
}

func (s *cond7[A, B, C, D, E, F, G, PA, PB, PC, PD, PE, PF, PG]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
	PC(&s.pc).InitParam(w)
	PD(&s.pd).InitParam(w)
	PE(&s.pe).InitParam(w)
	PF(&s.pf).InitParam(w)
	PG(&s.pg).InitParam(w)
}

func (s *cond7[A, B, C, D, E, F, G, PA, PB, PC, PD, PE, PF, PG]) Check(*ecs.World) bool {
	return s.f(&s.pa, &s.pb, &s.pc, &s.pd, &s.pe, &s.pf, &s.pg)
}

// Fn8 turns a function with 8 parameters into a system.
func Fn8[A, B, C, D, E, F, G, H any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E], PF paramPtr[F], PG paramPtr[G], PH paramPtr[H]](f func(PA, PB, PC, PD, PE, PF, PG, PH)) *SystemConfig {
	return newSystemConfig(funcName(f), &fn8[A, B, C, D, E, F, G, H, PA, PB, PC, PD, PE, PF, PG, PH]{f: f})
}

type fn8[A, B, C, D, E, F, G, H any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E], PF paramPtr[F], PG paramPtr[G], PH paramPtr[H]] struct {
	f  func(PA, PB, PC, PD, PE, PF, PG, PH)
	pa A
	pb B
	pc C
	pd D
	pe E
	pf F
	pg G
	ph H
}

func (s *fn8[A, B, C, D, E, F, G, H, PA, PB, PC, PD, PE, PF, PG, PH]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
	PC(&s.pc).InitParam(w)
	PD(&s.pd).InitParam(w)
	PE(&s.pe).InitParam(w)
	PF(&s.pf).InitParam(w)
	PG(&s.pg).InitParam(w)
	PH(&s.ph).InitParam(w)
}

func (s *fn8[A, B, C, D, E, F, G, H, PA, PB, PC, PD, PE, PF, PG, PH]) Run(*ecs.World) {
	s.f(&s.pa, &s.pb, &s.pc, &s.pd, &s.pe, &s.pf, &s.pg, &s.ph)
}

// Cond8 turns a function with 8 parameters that returns bool into a run condition.
func Cond8[A, B, C, D, E, F, G, H any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E], PF paramPtr[F], PG paramPtr[G], PH paramPtr[H]](f func(PA, PB, PC, PD, PE, PF, PG, PH) bool) Condition {
	return &cond8[A, B, C, D, E, F, G, H, PA, PB, PC, PD, PE, PF, PG, PH]{f: f}
}

type cond8[A, B, C, D, E, F, G, H any, PA paramPtr[A], PB paramPtr[B], PC paramPtr[C], PD paramPtr[D], PE paramPtr[E], PF paramPtr[F], PG paramPtr[G], PH paramPtr[H]] struct {
	f  func(PA, PB, PC, PD, PE, PF, PG, PH) bool
	pa A
	pb B
	pc C
	pd D
	pe E
	pf F
	pg G
	ph H
}

func (s *cond8[A, B, C, D, E, F, G, H, PA, PB, PC, PD, PE, PF, PG, PH]) Init(w *ecs.World) {
	PA(&s.pa).InitParam(w)
	PB(&s.pb).InitParam(w)
	PC(&s.pc).InitParam(w)
	PD(&s.pd).InitParam(w)
	PE(&s.pe).InitParam(w)
	PF(&s.pf).InitParam(w)
	PG(&s.pg).InitParam(w)
	PH(&s.ph).InitParam(w)
}

func (s *cond8[A, B, C, D, E, F, G, H, PA, PB, PC, PD, PE, PF, PG, PH]) Check(*ecs.World) bool {
	return s.f(&s.pa, &s.pb, &s.pc, &s.pd, &s.pe, &s.pf, &s.pg, &s.ph)
}
