#!/bin/sh
# Copies raylib-go's pure-Go files (types, colors, constants, raymath) from the
# version illusion depends on, so the web bridge exposes the same types. Like
# every file here they only build for js; lib.sh gives the directory the
# go.mod that makes it stand in for raylib-go. Run it after bumping raylib-go
# in the root go.mod.
set -eu
cd "$(dirname "$0")"
version=$(cd ../.. && go list -m -f '{{.Version}}' github.com/gen2brain/raylib-go/raylib)
(cd ../.. && go mod download github.com/gen2brain/raylib-go/raylib)
src=$(go env GOMODCACHE)/github.com/gen2brain/raylib-go/raylib@$version
for f in raylib.go raymath.go raymath_generated_methods.go; do
	{
		echo "// Code generated by sync.sh from raylib-go $version/$f. DO NOT EDIT."
		echo
		echo "//go:build js"
		echo
		grep -v '^//go:generate' "$src/$f" # raylib-go's generators aren't here
	} >"$f"
	chmod 644 "$f"
done
cp "$src/LICENSE" LICENSE && chmod 644 LICENSE
echo "$version" >UPSTREAM_VERSION
