// Code generated by update.sh. DO NOT EDIT.

#include "third_party/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitter.cpp"
#include "third_party/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitterBinning.cpp"
#include "third_party/JoltPhysics/Jolt/TriangleSplitter/TriangleSplitterMean.cpp"
