// Code generated by update.sh. DO NOT EDIT.

#include "third_party/JoltPhysics/Jolt/Physics/SoftBody/SoftBodyCreationSettings.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/SoftBody/SoftBodyMotionProperties.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/SoftBody/SoftBodyShape.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/SoftBody/SoftBodySharedSettings.cpp"
