// Code generated by update.sh. DO NOT EDIT.

#include "third_party/JoltPhysics/Jolt/Physics/Vehicle/MotorcycleController.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Vehicle/TrackedVehicleController.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Vehicle/VehicleAntiRollBar.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Vehicle/VehicleCollisionTester.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Vehicle/VehicleConstraint.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Vehicle/VehicleController.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Vehicle/VehicleDifferential.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Vehicle/VehicleEngine.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Vehicle/VehicleTrack.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Vehicle/VehicleTransmission.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Vehicle/Wheel.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Vehicle/WheeledVehicleController.cpp"
