// Code generated by update.sh. DO NOT EDIT.

#include "third_party/JoltPhysics/Jolt/Renderer/DebugRenderer.cpp"
#include "third_party/JoltPhysics/Jolt/Renderer/DebugRendererPlayback.cpp"
#include "third_party/JoltPhysics/Jolt/Renderer/DebugRendererRecorder.cpp"
#include "third_party/JoltPhysics/Jolt/Renderer/DebugRendererSimple.cpp"
