// Code generated by update.sh. DO NOT EDIT.

#include "third_party/JoltPhysics/Jolt/Physics/Body/Body.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Body/BodyCreationSettings.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Body/BodyInterface.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Body/BodyManager.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Body/MassProperties.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Body/MotionProperties.cpp"
