// Code generated by update.sh. DO NOT EDIT.

#include "third_party/JoltPhysics/Jolt/ObjectStream/ObjectStream.cpp"
#include "third_party/JoltPhysics/Jolt/ObjectStream/ObjectStreamBinaryIn.cpp"
#include "third_party/JoltPhysics/Jolt/ObjectStream/ObjectStreamBinaryOut.cpp"
#include "third_party/JoltPhysics/Jolt/ObjectStream/ObjectStreamIn.cpp"
#include "third_party/JoltPhysics/Jolt/ObjectStream/ObjectStreamOut.cpp"
#include "third_party/JoltPhysics/Jolt/ObjectStream/ObjectStreamTextIn.cpp"
#include "third_party/JoltPhysics/Jolt/ObjectStream/ObjectStreamTextOut.cpp"
#include "third_party/JoltPhysics/Jolt/ObjectStream/SerializableObject.cpp"
#include "third_party/JoltPhysics/Jolt/ObjectStream/TypeDeclarations.cpp"
