// Code generated by update.sh. DO NOT EDIT.

#include "third_party/JoltPhysics/Jolt/Geometry/ConvexHullBuilder.cpp"
#include "third_party/JoltPhysics/Jolt/Geometry/ConvexHullBuilder2D.cpp"
#include "third_party/JoltPhysics/Jolt/Geometry/Indexify.cpp"
#include "third_party/JoltPhysics/Jolt/Geometry/OrientedBox.cpp"
