// Code generated by update.sh. DO NOT EDIT.

#include "third_party/JoltPhysics/Jolt/Physics/Character/Character.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Character/CharacterBase.cpp"
#include "third_party/JoltPhysics/Jolt/Physics/Character/CharacterVirtual.cpp"
