// Code generated by update.sh. DO NOT EDIT.

#include "third_party/JoltPhysics/Jolt/Skeleton/SkeletalAnimation.cpp"
#include "third_party/JoltPhysics/Jolt/Skeleton/Skeleton.cpp"
#include "third_party/JoltPhysics/Jolt/Skeleton/SkeletonMapper.cpp"
#include "third_party/JoltPhysics/Jolt/Skeleton/SkeletonPose.cpp"
