#!/usr/bin/env bash
# Re-vendors Jolt Physics and regenerates the unity build files cgo compiles.
# Run from this directory:
#
#   ./update.sh [tag]
set -euo pipefail

JOLT_REPO=https://github.com/jrouwe/JoltPhysics.git
JOLT_TAG=${1:-v5.3.0}

here=$(cd "$(dirname "$0")" && pwd)
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

git clone -q --depth 1 --branch "$JOLT_TAG" "$JOLT_REPO" "$work/JoltPhysics"
commit=$(git -C "$work/JoltPhysics" rev-parse HEAD)

rm -rf "$here/third_party"
mkdir -p "$here/third_party/JoltPhysics"
cp -R "$work/JoltPhysics/Jolt" "$here/third_party/JoltPhysics/Jolt"
cp "$work/JoltPhysics/LICENSE" "$here/third_party/JoltPhysics/"
find "$here/third_party" \( -name "*.cmake" -o -name "*.natvis" \) -delete
echo "JoltPhysics $JOLT_REPO $JOLT_TAG ($commit)" > "$here/third_party/VERSION"

# cgo compiles every .cpp in the package directory. Group Jolt's sources into
# a few unity files by directory so the build stays reasonably fast.
group_of() { awk -F/ '{ print (NF > 3 ? $2 "_" $3 : $2) }' | sed 's/\.cpp$//'; }
rm -f "$here"/unity_*.cpp
cd "$here/third_party/JoltPhysics"
for group in $(find Jolt -name "*.cpp" | group_of | sort -u); do
  out="$here/unity_$(echo "$group" | tr '[:upper:]' '[:lower:]').cpp"
  {
    echo "// Code generated by update.sh. DO NOT EDIT."
    echo
    find Jolt -name "*.cpp" | sort | while read -r f; do
      if [ "$(echo "$f" | group_of)" = "$group" ]; then
        echo "#include \"third_party/JoltPhysics/$f\""
      fi
    done
  } > "$out"
done
echo "vendored Jolt $JOLT_TAG ($commit)"
